### ISSUE TITLE
Does not work in iOS 13.4.1

### ISSUE THREAD

**Issue by ArtemisGraphic** [madeInLagny/mil-no-sleep#2]
I'm trying to use this repo as alternative to nosleep.js but in the demo and in my webiste does not work on iOS 13.4.1. Any solution?

**Comment by madeInLagny** [comment]
Hi, I believe it is due to the format of the background video used. I will have a look at alternatives this week and post an update. Thanks for raising the issue.

**Comment by sdelice** [comment]
Hi, I have the same probeme. Did you fix it and post an update ?

**Comment by madeInLagny** [comment]
Hi, bug fixed in new version.
Enjoy :)

**Comment by sdelice** [comment]
Hi Mil, 
Hope you are doing well ! Thanks you for the fix. But i was not manege to adapt your module for my needs... What i want to do is to adapt the domo exemple for having jute on toggle button for enable /disable the Mil-no-Sleep... 
Something like this : 
https://www.bootstraptoggle.com/

Any help wil be appreciate !

**Comment by madeInLagny** [comment]
Hi @sdelice 
I have amended the demo to reflect how to handle a toggle button change event.
[https://stackblitz.com/edit/mil-no-sleep-example](url)

**Comment by sdelice** [comment]
That's great ! Thank you very much ! That's exactly what I want !
PS : I live near by you, in the city of Lognes... :-)

**Comment by madeInLagny** [comment]
Au plaisir de te rencontrer...

**Comment by sdelice** [comment]
> Hi @sdelice
> I have amended the demo to reflect how to handle a toggle button change event.
> [https://stackblitz.com/edit/mil-no-sleep-example](url)

Just a last behaviour enhancement request. In your exemple the toggle button is not checked. How to enable both the mil-no-sleep function and checked the toggle button by default when the page is loaded. I've try to put a this.noSleep.enableSleepMode() in the firstUpdated () but it trhow me an error : 
Uncaught (in promise) TypeError: Cannot read property 'pause' of undefined
    at HTMLElement.enableSleepMode 
    at HTMLElement.firstUpdated 
    at HTMLElement.performUpdate
    at HTMLElement._enqueueUpdate

I'm not very comfortable with the lit-element objects and evet lifecycle... :-(

**Comment by madeInLagny** [comment]
Add the following code to the firstUpdated method

const checkBox = this.shadowRoot.getElementById("toggleCheck");
    checkBox.checked = "checked";
    this.noSleep.disableSleepMode();
